"use strict";

import { action } from "../../../multifamily/common/store/rootaction";
import { CHECK_PREVIOUS_CHAT_SESSION, CLEAR_CHAT_MESSAGES, CLEAR_LIVEKIT_TOKEN, CONNECTED_TO_ROOM, FETCH_LIVEKIT_TOKEN, FETCH_PREVIOUS_CHAT_HISTORY, GET_LIVEKIT_TOKEN, HIDE_CHAT_WITH_US_MODAL, PERSIST_CHAT_SESSION_ID, PERSIST_LIVEKIT_TOKEN, PERSIST_PREVIOUS_CHAT_HISTORY, PERSIST_PREVIOUS_CHAT_SESSION, SEND_MESSAGE_TO_CHATWOOT, SHOW_CHATBOT_LOADER, SET_IS_LIVE_AGENT_CONNECTED, SET_LIVE_AGENT_HANDOFF_STATUS, SET_RECONNECT_TO_ROOM, SHOW_CHAT_WITH_US_MODAL, STORE_CHAT_MESSAGE, STORE_LIVE_AGENT_HANDOFF_DETAILS, TOGGLE_MESSAGE_LIKE, UPDATE_MESSAGE_LIKE, SET_LIVE_AGENT_TO_AI_HANDOFF, CHANGE_OWNERSHIP, SET_RECONNECT_ATTEMPT_ACTION, SET_CONNECTED_TO_ULTRON, PERSIST_CURRENT_PROP_ID, SET_CURRENT_AI_SCREEN_NAME } from "./actionTypes.js";
export const showChatBotLoaderAction = payload => action(SHOW_CHATBOT_LOADER, payload);
export const showChatWithUsModalAction = payload => action(SHOW_CHAT_WITH_US_MODAL, payload);
export const setCurrentAIScreenNameAction = payload => action(SET_CURRENT_AI_SCREEN_NAME, payload);
export const hideChatWithUsModalAction = () => action(HIDE_CHAT_WITH_US_MODAL);
export const setReconnectionAttemptAction = payload => action(SET_RECONNECT_ATTEMPT_ACTION, payload);
export const getLivekitTokenAction = payload => action(GET_LIVEKIT_TOKEN, payload);
export const fetchLivekitTokenAction = payload => action(FETCH_LIVEKIT_TOKEN, payload);
export const persistLivekitTokenAction = payload => action(PERSIST_LIVEKIT_TOKEN, payload);
export const clearLivekitTokenAction = () => action(CLEAR_LIVEKIT_TOKEN);
export const setReconnectToRoomAction = payload => action(SET_RECONNECT_TO_ROOM, payload);
export const setConnectedToRoomAction = payload => action(CONNECTED_TO_ROOM, payload);
export const setConnectedToUltronAction = payload => action(SET_CONNECTED_TO_ULTRON, payload);
export const checkPreviousChatSessionAction = () => action(CHECK_PREVIOUS_CHAT_SESSION);
export const persistChatSessionIdAction = payload => action(PERSIST_CHAT_SESSION_ID, payload);
export const persistPreviousChatSessionDetailsAction = payload => action(PERSIST_PREVIOUS_CHAT_SESSION, payload);
export const fetchPreviousChatHistoryAction = payload => action(FETCH_PREVIOUS_CHAT_HISTORY, payload);
export const persistPreviousChatHistoryAction = payload => action(PERSIST_PREVIOUS_CHAT_HISTORY, payload);
export const storeChatMessageAction = payload => action(STORE_CHAT_MESSAGE, payload);
export const clearChatMessagesAction = () => action(CLEAR_CHAT_MESSAGES);
export const toggleMessageLikeAction = payload => action(TOGGLE_MESSAGE_LIKE, payload);
export const updateMessageLikeAction = payload => action(UPDATE_MESSAGE_LIKE, payload);
export const storeLiveAgentHandoffDetailsAction = payload => action(STORE_LIVE_AGENT_HANDOFF_DETAILS, payload);
export const setLiveAgentHandoffStatusAction = payload => action(SET_LIVE_AGENT_HANDOFF_STATUS, payload);
export const setIsLiveAgentConnectedAction = payload => action(SET_IS_LIVE_AGENT_CONNECTED, payload);
export const sendMessageToChatwootAction = payload => action(SEND_MESSAGE_TO_CHATWOOT, payload);
export const setLiveAgentToAIHandoffAction = payload => action(SET_LIVE_AGENT_TO_AI_HANDOFF, payload);
export const changeChatOwnershipAction = () => action(CHANGE_OWNERSHIP);
export const persistCurrentPropIdAction = payload => action(PERSIST_CURRENT_PROP_ID, payload);
//# sourceMappingURL=actions.js.map